<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <RootNamespace>Rina.Shell</RootNamespace>
    <AssemblyName>Rina.Shell</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Rina.Protocol\Rina.Protocol.csproj" />
  </ItemGroup>
</Project>
