# -*- coding: utf-8 -*-
"""
Порождение контракта для оболочки из снимка протокола.

Задача плана 4.0-F02.

Оболочка пишется на другом языке, и у неё неизбежно появятся имена методов,
событий и кодов ошибок. Написать их руками — значит завести **третий**
список: спецификация, ядро, оболочка. Первые два уже сверяются (4.0-D05,
D11, D17); третий разошёлся бы с ними при первом же добавлении, причём
незаметно — опечатка в имени метода выглядит как метод.

Поэтому C#-часть порождается из `docs/protocol/contract-v1.json` — того же
снимка, с которым сверяется код ядра. Один источник, две стороны.

Порождаются только **имена и свойства**: методы, события, коды ошибок с их
категорией и повторяемостью, возможности, виды потоков. Поведение не
порождается: сгенерированный код, который что-то делает, читать труднее, чем
написанный, а выгоды здесь никакой — вся логика и так одинакова с обеих
сторон только по смыслу, но не по устройству.

Запуск:
    python tools/gen_csharp_contract.py            записать
    python tools/gen_csharp_contract.py --check    сверить, не переписывая
"""

import json
import os
import sys

from console import use_utf8

use_utf8()

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SNAPSHOT = os.path.join(ROOT, "docs", "protocol", "contract-v1.json")
OUT = os.path.join(ROOT, "shell", "Rina.Protocol", "Generated", "Contract.g.cs")


def ident(name: str) -> str:
    """`command.handle` -> `CommandHandle`, `protocol.not_ready` -> ..."""
    parts = name.replace("-", ".").replace("_", ".").split(".")
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


def render(contract: dict) -> str:
    methods = sorted(contract["methods"])
    events = sorted(contract["events"])
    errors = sorted(contract["errors"])
    caps = sorted(contract["capabilities"])
    kinds = sorted(contract["stream_kinds"])
    scopes = sorted(contract["scopes"])

    lines = [
        "// <auto-generated>",
        "//   Порождено из docs/protocol/contract-v1.json.",
        "//   Не править руками: правьте контракт и перезапустите",
        "//   python tools/gen_csharp_contract.py",
        "//",
        "//   Зачем так: имена, написанные в оболочке отдельно, стали бы",
        "//   третьим списком рядом со спецификацией и ядром — и разошлись",
        "//   бы с ними при первом добавлении, причём незаметно, потому что",
        "//   опечатка в имени метода выглядит как метод.",
        "// </auto-generated>",
        "",
        "#nullable enable",
        "",
        "namespace Rina.Protocol;",
        "",
        "/// <summary>Версия протокола, под которую собрана оболочка.</summary>",
        "public static class ProtocolVersion",
        "{",
        f"    public const int Current = {contract['protocol_version']};",
        "}",
        "",
        "/// <summary>Имена управляющих методов (§6 спецификации).</summary>",
        "public static class Methods",
        "{",
    ]
    for name in methods:
        cap = contract["methods"][name]
        note = f"Возможность: {cap}." if cap else "Базовый метод."
        lines.append(f"    /// <summary>{note}</summary>")
        lines.append(f'    public const string {ident(name)} = "{name}";')
    lines += [
        "",
        "    /// <summary>Какая возможность отпирает метод; null — базовый.</summary>",
        "    public static readonly IReadOnlyDictionary<string, string?> Capability =",
        "        new Dictionary<string, string?>",
        "        {",
    ]
    for name in methods:
        cap = contract["methods"][name]
        value = f'"{cap}"' if cap else "null"
        lines.append(f'            ["{name}"] = {value},')
    lines += ["        };", "}", ""]

    lines += [
        "/// <summary>Имена событий ядра (§6, §7, §9, §10).</summary>",
        "public static class Events",
        "{",
    ]
    for name in events:
        fields = contract["events"][name]
        shape = ", ".join(
            f"{f}: {d['type']}" + ("" if d.get("required", True) else "?")
            for f, d in sorted(fields.items())) or "без полей"
        lines.append(f"    /// <summary>{shape}</summary>")
        lines.append(f'    public const string {ident(name)} = "{name}";')
    lines += [
        "",
        "    /// <summary>Все объявленные события. Незнакомое игнорируется молча.</summary>",
        "    public static readonly IReadOnlySet<string> All = new HashSet<string>",
        "    {",
    ]
    for name in events:
        lines.append(f'        "{name}",')
    lines += ["    };", "}", ""]

    lines += [
        "/// <summary>Категория ошибки (§5).</summary>",
        "public enum ErrorCategory { User, System, Protocol }",
        "",
        "/// <summary>Строка каталога ошибок: чем ошибка является.</summary>",
        "/// <param name=\"Category\">Кто виноват.</param>",
        "/// <param name=\"Retryable\">Имеет ли смысл повторить то же самое.</param>",
        "public readonly record struct ErrorSpec(ErrorCategory Category, bool Retryable);",
        "",
        "/// <summary>Каталог кодов ошибок (§5).</summary>",
        "public static class ErrorCodes",
        "{",
    ]
    for code in errors:
        spec = contract["errors"][code]
        lines.append(
            f"    /// <summary>{spec['category']}, "
            f"{'повторяемая' if spec['retryable'] else 'неповторяемая'}.</summary>")
        lines.append(f'    public const string {ident(code)} = "{code}";')
    lines += [
        "",
        "    /// <summary>Категория и повторяемость принадлежат коду, а не месту вызова.</summary>",
        "    public static readonly IReadOnlyDictionary<string, ErrorSpec> Catalogue =",
        "        new Dictionary<string, ErrorSpec>",
        "        {",
    ]
    for code in errors:
        spec = contract["errors"][code]
        cat = spec["category"].capitalize()
        retry = "true" if spec["retryable"] else "false"
        lines.append(
            f'            ["{code}"] = new(ErrorCategory.{cat}, {retry}),')
    lines += ["        };", "}", ""]

    lines += [
        "/// <summary>Возможности сторон (§4).</summary>",
        "public static class Capabilities",
        "{",
    ]
    for name in caps:
        spec = contract["capabilities"][name]
        lines.append(f"    /// <summary>Объявляет {spec['side']}.</summary>")
        lines.append(f'    public const string {ident(name)} = "{name}";')
    shell = sorted(n for n in caps
                   if contract["capabilities"][n]["side"] == "shell")
    lines += [
        "",
        "    /// <summary>Что объявляет оболочка в рукопожатии.</summary>",
        "    public static readonly string[] Shell =",
        "    [",
    ]
    for name in shell:
        lines.append(f'        "{name}",')
    lines += ["    ];", "}", ""]

    lines += [
        "/// <summary>Виды двоичных потоков (§8) и нужная возможность.</summary>",
        "public static class StreamKinds",
        "{",
        "    public static readonly IReadOnlyDictionary<string, string> Capability =",
        "        new Dictionary<string, string>",
        "        {",
    ]
    for kind in kinds:
        lines.append(f'            ["{kind}"] = "{contract["stream_kinds"][kind]}",')
    lines += ["        };", "}", ""]

    lines += [
        "/// <summary>Области разрешения (§11).</summary>",
        "public static class Scopes",
        "{",
    ]
    for scope in scopes:
        lines.append(f'    public const string {ident(scope)} = "{scope}";')
    lines += ["}", ""]
    return "\n".join(lines)


def main(argv) -> int:
    with open(SNAPSHOT, encoding="utf-8") as f:
        contract = json.load(f)
    text = render(contract)

    if "--check" in argv:
        if not os.path.isfile(OUT):
            print("порождённого файла нет; запустите без --check")
            return 1
        with open(OUT, encoding="utf-8") as f:
            current = f.read()
        if current != text:
            print("Contract.g.cs разошёлся со снимком протокола.")
            print("Перезапустите: python tools/gen_csharp_contract.py")
            return 1
        print("Contract.g.cs сходится со снимком")
        return 0

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"порождено: {os.path.relpath(OUT, ROOT)}")
    print(f"  методов {len(contract['methods'])}, "
          f"событий {len(contract['events'])}, "
          f"кодов ошибок {len(contract['errors'])}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
